class Employee {
  int id;
  String amharic_name;
  String oromic_name;
  String english_name;
  String position;
  String oromic_position;
  String english_position;
  String path;
  String office;
  int team_id;
  bool hasSub = false;
  Employee(
      this.id,
      this.amharic_name,
      this.oromic_name,
      this.english_name,
      this.position,
      this.oromic_position,
      this.english_position,
      this.path,
      this.office,
      this.team_id,
      {this.hasSub = false});
}

// List<Employee> Employees = [
//   Employee(25, 'አወቀ ታደሰ', 'Aweke Tadese', 'Hogganaa Damee', 'AwekeTadese.jpg',
//       'ቅርንጫፍ ስራ አስኪያጅ', '40'),
//   Employee(22, 'ራህመት', 'Rahmat', 'Ogeessa tajaajila hayyama konkolaataa',
//       'Rahmet.jpg', 'ጸሃፊ', '40'),
//   Employee(
//       11,
//       "ዘሚካኤል የማነ",
//       "Zamikael Yamaana",
//       "Dursaa Garee Qorannoo Gahumsa Konkolaataa.",
//       "zemichael.jpg",
//       "የተሽከርካሪ ብቃት  ምርመራ  ቡድን መሪ",
//       "1-4"),
//   Employee(26, 'መብራት ሀጎስ', 'Mebrat Hagos ', 'Daayireektara hayyama konkolaataa',
//       'MebratHagos.jpg', 'የአሽከርካሪ ብቃት  አገልግሎት  ዳይሬክተር', '31'),
//   Employee(
//       20,
//       'ፋኖስ መኮነን',
//       'Fanos Makonnen',
//       'Daayireektara hayyama konkolaataa',
//       'FanosMekonen.jpg',
//       'የተሽከርካሪ ብቃት  አገልግሎት ዳይሬክተር',
//       '28'),
//   Employee(
//       31,
//       'ያየሽ መኮነን',
//       'Yayesh Mekonen',
//       'Dursaa Garee Odiitii Qulqullinaa .',
//       '',
//       'የአገልግሎት ጥራት ኦዲት  ቡድን መሪ',
//       '25'),
//   Employee(27, 'ትዕግስት ተምትም', 'Tigist Temtem', 'Deeskii Odeeffannaa',
//       'TigistTemtm.jpg', 'መረጃ ዴስክ', '-'),
//   Employee(30, 'ዮሀንስ ሙሉጌታ', 'Yohannes Mulgeta', 'Ogeessa ICT',
//       'YohannesMulugeta.jpg', 'የICT ባለሙያ', '-'),
//   Employee(32, 'አለም ነዲ', 'Alam Nadhi', 'Dursaa Garee Faayinaansi', '',
//       'ፋይናንስና ግዢ ቡድን መሪ', '43'),
//   Employee(
//       46, 'ማሪቱ ጎላ', 'Maritu Gollaa', 'Qabeenya Namaa', '', 'የሰው ሀብት', '44'),
//   Employee(
//       43,
//       'ተፈራ በቀለ',
//       'Tafaraa Baqala',
//       'Ogeessa Naamusaa Fi Farra Malaamaltummaa',
//       '',
//       'የስነ ምግባርና ፀረ ሙስና ዳይሬክተር',
//       '44'),
//   Employee(
//       44,
//       'ዘላለም መስጋነው',
//       'Zalaalam Misgaanaw',
//       'Hogganaa Garee Tajaajila Gahumsa Konkolaachisaa ',
//       '',
//       'የአሽከርካሪ ብቃት  አገልግሎት ቡድን መሪ',
//       '43'),
//   Employee(
//       45, 'አማን ገመቹ', 'Tafaraa Baqala', 'Garee Qabeenyaa', '', 'ንብረት ክፍል', '48'),
//   Employee(
//       34,
//       'አበበች ሞገስ',
//       'Ababach  Mogas',
//       'Hogganaa garee galmee konkolaataa fi kuusaa',
//       '',
//       'የተሽከርካሪ  ሪከርድና ማህደር ቡድን መሪ',
//       '27'),
// ];

// List<Employee> EmployeesRated = [
//   Employee(25, 'አወቀ ታደሰ', 'Aweke Tadese', 'Hogganaa Damee', 'AwekeTadese.jpg',
//       'ቅርንጫፍ ስራ አስኪያጅ', '40'),
//   Employee(22, 'ራህመት', 'Rahmat', 'Ogeessa tajaajila hayyama konkolaataa',
//       'Rahmet.jpg', 'ጸሃፊ', '40'),
//   Employee(
//       2,
//       "ታምራት ገታነህ",
//       "Tamirat Getanah",
//       "Ogeessa tajaajila hayyama konkolaataa",
//       "tamirat.jpg",
//       "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ",
//       "-"),
//   Employee(
//       1,
//       "ተዘራ ፍሬው",
//       "Tezera Firew",
//       "Ogeessa tajaajila hayyama konkolaataa",
//       "tezera.jpg",
//       "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ",
//       "-"),
//   Employee(
//       3,
//       "ዙፋን መክብብ",
//       "Zufan Makbib",
//       "Ogeessa tajaajila hayyama konkolaataa",
//       "zufan.jpg",
//       "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ",
//       "-"),
//   Employee(
//       4,
//       "ጥላሁን ሚኒልክ አየለ",
//       "Tilahun Minilik Ayala",
//       "Ogeessa tajaajila hayyama konkolaataa",
//       "tilahun.jpg",
//       "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያion",
//       "-"),
//   Employee(
//       5,
//       "ከተማ መርጋ ዳባ",
//       "Katama Margaa Dhaabaa",
//       "Ogeessa tajaajila hayyama konkolaataa",
//       "ketema.jpg",
//       "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ",
//       "14"),
//   Employee(
//       6,
//       "ማንዲሱ ጂማ ካራ",
//       "Mandisu Jimmaa Kaarraa",
//       "Ogeessa tajaajila hayyama konkolaataa",
//       "Mandisu.jpg",
//       "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ",
//       "15"),
//   Employee(
//       17,
//       "ጻዳለ በርሄ ዘርጋው",
//       "Tsadaala Barhe Zargaw",
//       "Ogeessa tajaajila hayyama konkolaataa",
//       "Mandisu.jpg",
//       "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ",
//       "16"),
//   Employee(
//       7,
//       "ለማነው ዋሴ መላኩ",
//       "Lamanaw Wase Malaaku",
//       "Ogeessa tajaajila hayyama konkolaataa",
//       "lamenew.jpg",
//       "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ",
//       "17"),
//   Employee(19, 'ደሴ ማሩ', 'Desse Maru', 'Ogeessa tajaajila hayyama konkolaataa',
//       'DeseMaru.jpg', 'የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ', '18'),
//   Employee(9, "ጸጋ ወርቅነህ", "Tsaggaa Warqnah", "Ogeessa Gahumsa Konkolaataa.",
//       "tsega.jpg", "የተሽከርካሪ ብቃት ምርመራ ባለሙያ", "1-4"),
//   Employee(10, "እፍሬም አበራ ", "Efrem Abarraa", "Ogeessa Gahumsa Konkolaataa.",
//       "ephrem.jpg", "የተሽከርካሪ ብቃት ምርመራ ባለሙያ", "1-4"),
//   Employee(
//       11,
//       "ዘሚካኤል የማነ",
//       "Zamikael Yamaana",
//       "Dursaa Garee Qorannoo Gahumsa Konkolaataa.",
//       "zemichael.jpg",
//       "የተሽከርካሪ ብቃት  ምርመራ  ቡድን መሪ",
//       "1-4"),
//   Employee(13, "ፉኣድ ሁሴን", "Fuad Husen", "Ogeessa Gahumsa Konkolaataa.",
//       "fuad.jpg", "የተሽከርካሪ ብቃት ምርመራ ባለሙያ", "1-4"),
//   Employee(12, "በሱፊቃድ ሲሳይ", "Basufikad Sisay", "Ogeessa Gahumsa Konkolaataa.",
//       "besufikad.jpg", "የተሽከርካሪ ብቃት ምርመራ ባለሙያ", "1-4"),
//   Employee(15, "ግርማ ወልዴ", "Girma Walde", "Ogeessa hayyama konkolaachisummaa",
//       "girma.jpg", "የ አሽከርካሬ ፍቃድ ባለሙያ", "31"),
//   Employee(
//       28,
//       'ሽኩሪያ ሀያቱ',
//       'Shukriya Hayatu',
//       'Ogeessa tajaajila hayyama konkolaataa',
//       'ShukriyaHayatu.jpg',
//       'የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ',
//       '33'),
//   Employee(14, "አስቴር ገመቹ", "Aster Gamachu", "Enkoodara deetaa konkolaachisaa",
//       "aster.jpg", "የ አሽከርካሪ ዳታ ኢንኮደር ", "35"),
//   Employee(
//       29,
//       'ውባለም ብርሀኑ',
//       'Wubalem Birhanu',
//       'Ogeessa tajaajila hayyama konkolaataa',
//       'wubalemBirhanu.jpg',
//       'የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ',
//       '38'),
//   Employee(26, 'መብራት ሀጎስ', 'Mebrat Hagos ', 'Daayireektara hayyama konkolaataa',
//       'MebratHagos.jpg', 'የአሽከርካሪ ብቃት  አገልግሎት  ዳይሬክተር', '31'),
//   Employee(
//       20,
//       'ፋኖስ መኮነን',
//       'Fanos Makonnen',
//       'Daayireektara hayyama konkolaataa',
//       'FanosMekonen.jpg',
//       'የተሽከርካሪ ብቃት  አገልግሎት ዳይሬክተር',
//       '28'),
//   Employee(
//       16,
//       "ንጋቱ ያዘንጋው",
//       "Nigatu Yazangaw",
//       "Ogeessa odiitii qulqullina tajaajilaa",
//       "zufan.jpg",
//       "የ አገልግሎት ጥራት ኦዲት ባለሙያ",
//       "25"),
//   Employee(18, "ታዬ ዘውዱ", "Taye Zawdu", "Ogeessa odiitii qulqullina tajaajilaa",
//       "", "የ አገልግሎት ጥራት ኦዲት ባለሙያ", "25"),
//   Employee(
//       31,
//       'ያየሽ መኮነን',
//       'Yayesh Mekonen',
//       'Dursaa Garee Odiitii Qulqullinaa Raawwii.',
//       '',
//       'የአገልግሎት ጥራት ኦዲት  ቡድን መሪ',
//       '25'),
//   Employee(
//       21,
//       'ትዕግስት ተስፋየ',
//       'Tigist Tesfay',
//       'Ogeessa  Odiitii Qulqullinaa Raawwii',
//       'TigistTesfay.jpg',
//       'የአገልግሎት ጥራት ኦዲት ባለሙያ',
//       '25'),
//   Employee(27, 'ትዕግስት ተምትም', 'Tigist Temtem', 'Deeskii Odeeffannaa',
//       'TigistTemtm.jpg', 'መረጃ ዴስክ', '-'),
//   Employee(30, 'ዮሀንስ ሙሉጌታ', 'Yohannes Mulgeta', 'Ogeessa ICT',
//       'YohannesMulugeta.jpg', 'የICT ባለሙያ', '-'),
//   Employee(32, 'አለም ነዲ', 'Alam Nadhi', 'Dursaa Garee Faayinaansi', '',
//       'ፋይናንስና ግዢ ቡድን መሪ', '43'),
//   Employee(
//       34,
//       'ተፈራ በቀለ',
//       'Tafaraa Baqala',
//       'Ogeessa Naamusaa Fi Farra Malaamaltummaa',
//       '',
//       'የስነ ምግባርና ፀረ ሙስና ዳይሬክተር',
//       '44'),
//   Employee(35, "በውቀት ደምለው", "Bewketu Demlew", "Ogeessa Haayyama konkolaataa",
//       "", "የተሽከርካሪ ፈቃድ  አገልግሎት  ባለሙያ ", "12"),
//   Employee(36, "ሰላም ተሰራ", "Selam Tesera", "Ogeessa Haayyama konkolaataa", "",
//       "የተሽከርካሪ ፈቃድ  አገልግሎት  ባለሙያ", "13"),
//   Employee(37, "ደረጄ ሸዋአመነ", "Darajjee Shawaamana",
//       "Ogeessa Haayyama konkolaataa", "", "የተሽከርካሪ ፈቃድ  አገልግሎት  ባለሙያ", "19"),
//   Employee(
//       38,
//       "ዘላለም መስጋነው",
//       "Darajjee Shawaamana",
//       "Dursaa Garee Haayyama konkolaachisaa",
//       "",
//       "አሽከርካሪ ብቃት  አገልግሎት ቡድን መሪ",
//       "24"),
//   Employee(
//       39,
//       "ፍሬው ተሻለ",
//       "Darajjee Shawaamana",
//       "Ogeessa Odiitii Qulqullinaa Tajaajilaaa",
//       "",
//       "የአገልግሎት ጥራት ኦዲት ባለሙያ",
//       "25"),
//   Employee(
//       40,
//       "ሮማን ዲበኩሎ",
//       "Darajjee Shawaamana",
//       "Ogeessa Odiitii Qulqullinaa Tajaajilaa",
//       "",
//       "የአገልግሎት ጥራት ኦዲት ባለሙያ",
//       "25"),
//   Employee(41, "አማን ገመቹ", "Darajjee Shawaamana", "Garee Qabeenya ", "",
//       "ንብረት ክፍል", "48"),
//   Employee(42, "ማሪቱ ጎላ", "Darajjee Shawaamana", "Qabeenya Namaa", "", "የሰው ሀብት",
//       "45"),
// ];

// List<Employee> Employees=[
//     Meseret Aseffaa
// Yilmaa Siisaay
// Girmaa Fiqaaduu
// Olii Yemaanee
// Takatal Temesgeen
// Malkee Goobanaa
// Shimelis Laggasaa
// Caaltuu Liyoo
// Lammii Ilaalaa
// Nigusee Baqqalaa
// Adunyaa Irranaa
// Bilisee Hirkoo
// Balaay Geetaachoo
// Saamu’el Gadaa
// Siisaay Hayiluu
// Isaa Guyyee
// Ahimed Yesuuf
// Yemaanee Yiggezuu
// Ancaaluu Leencoo
// Aliyoo Golee
// Gammadaa Waaq-jiraa
// Zinash Gebreweld
// Qaasim Ahimed
// Biyyaa Raayyaa
// Fufaa Laggasaa
// Abbebbee Leellisaa
// ];

List<Employee> Employees = [
  Employee(1, 'አወቀ ታደሰ በዛብህ', 'Aweqe tadse', 'Aweke tadese ', 'ዋና ስራ አስኪያጅ',
      'Darectara Tajajila konkolootaaa', 'Manager', 'AwekeTadese.jpg', '40', 0,
      hasSub: true),
  Employee(
      2,
      'መብራት ሀጎስ',
      'Mebraat Haggos ',
      'Mebrat Hagos',
      'የአሽከርካሪ ብቃት ማረጋገጥ ዳይሬክተር',
      'Hogganaa Damee',
      'Driver Service Director',
      '',
      '30',
      0,
      hasSub: true),
  Employee(
      3,
      'ፋኖስ መኮንን ',
      'Fanos Mekonen Gemeda',
      'Faanoos Makonnin ',
      'የተሸከርካሪ ብቃት ማረጋገጥ ፈቃድ አገልግሎት ዳይሬክተር',
      'Darectara Tajajila konkolootaaa',
      'Vehicle Service Director',
      'FanosMekonnen.jpg',
      '28',
      0,
      hasSub: true),
  Employee(
      4,
      'ኩኖ ዋቅጅራ',
      'Kuno Wakejra',
      'Kuunoo waqjiraa',
      'የግዥ፣ ፋይናንስና ንብረት አስተዳደር ዳይሬክተር',
      'Darekatara Faaynansii',
      'Finance and Asset Management Director',
      'KennoWakjira.jpg',
      '42',
      0,
      hasSub: true),
  Employee(
      5,
      'ያየሽ መኮንን',
      'Yaayesh Makonnin',
      'Yayesh Mekonen',
      'የአገልግሎት ጥራት ኦዲት ቡድን መሪ',
      'Hoganaa garee odiitii',
      'Audit team leader',
      '',
      '25',
      0,
      hasSub: true),
  Employee(
      6,
      'ዘሚካኤል የማነ አሰፋ',
      'Zamikaael Yemaana',
      'Zemikael Yemane Asefa',
      'የተሸከርካሪ ብቃት ማረጋገጥ ቡድን መሪ',
      'Dursaa garee Ogeessa Teekniikaa',
      'Vehicle Technical Inspection Team Leader',
      'ZemichaelYemane.jpg',
      '1',
      0,
      hasSub: true),
  // Team Manager
  Employee(
      7,
      'ራህመት ሁሴን መሀመድ',
      'Rahmet Hussene ',
      'Rahmet Hussene',
      'ኤክስኩቲቭ ሴክሬተሪ',
      'Barreessitu Hoji-geggeessaa',
      'Executive secretaries ',
      'RahmetHussen.jpg',
      '40',
      1),
  Employee(8, 'ዮሃንስ ሙሉጌታ', 'Yohanes Mullugeta', 'Yohannes Mulugeta ',
      'አይ ሲቲ ባለሙያ', 'ICT', 'ICT', 'YohannesMulugeta.jpg', '41', 1),

  // Team Driver Service
  Employee(
      9,
      'ግርማ ወልዴ ለማ',
      'Girmaa Weldee ',
      'Girma Welde',
      'የአሽከርካሪ አገልግሎት ባለሙያ',
      'Ogeessa tajajilaa konkolootaaa',
      'Driver Service officer',
      'GirmaWolde.jpg',
      '31',
      2),
  Employee(
      10,
      'ጌቱ ብርሃኑ ሁሪሳ',
      'Getu Beraanu ',
      'Getu Brhanu',
      'የአሽከርካሪ አገልግሎት ባለሙያ',
      'Ogeessa tajajilaa konkolootaaa',
      'Driver Service officer',
      'GetuBerhanu.jpg',
      '32',
      2),
  Employee(
      11,
      'ሽኩሪያ ሀያቱ ሻሚል',
      'Shekuriya Hayatu ',
      'Shekuriiya Hayyatu ',
      'የአሽከርካሪ አገልግሎት ባለሙያ',
      'Ogeessa tajajilaa konkolootaaa',
      'Driver Service officer',
      'ShukriyaHayatu.jpg',
      '33',
      2),
  Employee(
      12,
      'አስቴር ገመቹ አብዲሳ',
      'Astter Gemechuu ',
      'Aster Gemechu',
      'የአሽከርካሪ ዳታ ኢንከደር',
      'Daataa inkoderaa',
      'Data incoder',
      'AsterGemechu.jpg',
      '31',
      2),

  // Team Vehicle Service
  Employee(
      13,
      'ዘላለም  ምስጋና ',
      'Ogeessa tajajilaa konkolootaaa',
      'Zelalem Misgana',
      'የተሸከርካሪ ፈቃድ አገልግሎት ቡድን መሪ',
      'Dursaa goree Tajajila konkolootaaa',
      'Driver Service officer',
      'ZelalemMesgane.jpg',
      '24',
      3),
  Employee(
      14,
      'ታምራት ጌታነህ',
      'Taamiraat Getaana',
      'Tamrat Getaneh',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'TamiratGetaneh.jpg',
      '7',
      3),
  Employee(
      15,
      'ተዘራ ፍሬው',
      'Tazarraa Fireew',
      'Tezera Ferew',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'TezeraFirew.jpg',
      '17',
      3),
  Employee(
      16,
      'ዙፋን መክብብ',
      'Zufan Makbib',
      'Zufan Mekebeb',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'ZufanMekbeb.jpg',
      '15',
      3),
  Employee(
      17,
      'ጥላሁን ሚኒሊክ ',
      'Xilaahun Minilik',
      'Tilhun Minilik',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'TilahunMinilik.jpg',
      '12',
      3),
  Employee(
      18,
      'ሰላም ተሰራ',
      'Salaam Tasaraa',
      'Selam Tesera',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'SelamTesera.jpg',
      '14',
      3),
  Employee(
      19,
      'ከተማ መርጋ',
      'Katamaa Margaa',
      'Ketema Merga',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'KetemaMerga.jpg',
      '11',
      3),
  Employee(
      20,
      'መሃዲሱ ጅማ',
      'Mahaandisuu Jamaa',
      'Mehandisu Jema',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      '',
      '19',
      3),
  Employee(
      21,
      'ፀዳለ በርሄ',
      'Tsedale Barhee',
      'Tsedale Berhe',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'Tsedale.jpg',
      '13',
      3),
  Employee(
      22,
      'ላመነው ዋሴ',
      'Laamanaw Waasee',
      'Lamenew Wase',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'LamenewWase.jpg',
      '9',
      3),
  Employee(
      23,
      'ደረጄ ሸዋአመነ',
      'Derejjee ShawaaAmenee',
      'Dereje ShewaAmene',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'DerejeShewa.jpg',
      '16',
      3),
  Employee(
      24,
      'መብራቱ መኮንን',
      'Mabraatee Makonniin',
      'Mebrate Mekonin',
      'የተሸከርካሪ ዳታ ኢንኮደር ባለሙያ ',
      'Daataa Inkoodarii',
      'Data in coder ',
      'MebratuMekonne.jpg',
      '26',
      3),
  Employee(
      25,
      'በውቀት ደምለው',
      'Bawqatu Damlaw ',
      'Bewketu Demilew',
      'መረጃ ዴስክ',
      'Deeskii Odeefannoo',
      'Information Desk officer',
      'BewketuDemlew.jpg',
      '10',
      3),
  Employee(
      26,
      'መልካምፍሬ አዳነ',
      'Mabraatee Makonniin',
      'Mebrate Mekonin',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'MelkamFireAdane.jpg',
      '',
      3),
  Employee(
      27,
      'ትዕግስት አዳነ',
      'Mabraatee Makonniin',
      'Mebrate Mekonin',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      '',
      '',
      3),

  // Finanace Team
  Employee(
      28,
      'እየሩሰ ደሳለኝ',
      'Iyaruus Dasaakany',
      'Eyerus desalegn',
      'የፋይናንስ ቡድን መሪ',
      'Dursaa garee faynansii',
      'Finance team leader ',
      'EyerusalemDesalegn.jpg',
      '42',
      4),
  Employee(29, 'ትናኝ ችሎት', 'Tanaanyi chiloot', 'Tenagn Chelot', 'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii', 'Accountant', '', '42', 4),
  Employee(30, 'ድርቤ ዘውዴ', 'Daribee Zawdee', 'Deribe Zewde', 'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii', 'Accountant', 'DiribeZewde.jpg', '42', 4),
  Employee(31, 'ሰለሞን ታዬ', 'Salamoon Taayyee', 'Solomon Taye', 'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii', 'Accountant', 'SolomonTaye.jpg', '42', 4),
  Employee(32, 'እታገኝ አስፋው', 'Itaagany Asfaaw', 'Etagegnew Asfaw', 'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii', 'Accountant', 'EtagegnAsfaw.jpg', '42', 4),
  Employee(
      33,
      'ውብዓለም ብርሃኑ ',
      'Wubaalam Birhaanu',
      'Wubalem Birhanu',
      'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii',
      'Accountant',
      'WubalemBirhanu.jpg',
      '42',
      4),
  Employee(34, 'ብርቅነሽ አያሌው', 'Birqinash Ayaalew', 'Birkinesh Ayalew',
      'የሂሳብ ባለሙያ', 'Ogeessa  faynansii', 'Accountant', 'Berknesh.jpg', '42', 4),
  Employee(35, 'ሰርካለም ጌታነህ', 'Sarkaalam Getaanah', 'Serkalem Getaneh',
      'የሂሳብ ባለሙያ', 'Ogeessa  faynansii', 'Accountant', 'Serkalem.jpg', '42', 4),
  Employee(36, 'ገነት ጌታ', 'Gannat Geetaa', 'Genet Geta', 'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii', 'Accountant', 'GenetGeta.jpg', '42', 4),
  // Team Odit
  Employee(
      37,
      'አብዲዋቅ ቦከና',
      'Abdiwaaq Bokennaa',
      'Abdiwak Bokena',
      'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi',
      'Auditor',
      '',
      '25',
      5),
  Employee(38, 'ታዬ ዘውዱ', 'Tayyee Zawduu', 'Taye Zewdu', 'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi', 'Auditor', 'TayeZewdu.jpg', '25', 5),
//   Employee(
//       39,
//       'አብዲዋቅ ቦከና',
//       'Abdiwaaq Bokennaa',
//       'Abdiwak Bokena',
//       'የአገልግሎት ጥራት ኦዲት ባለሙያ',
//       'Ogeessa tajajilaa Oditi',
//       'Auditor',
//       'AwekeTadese.jpg',
//       '25',
//       5),
  Employee(
      40,
      'ትዕግስት ተስፋዬ',
      'Tigist Tasfaye',
      'Tigist Tesfaye',
      'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi',
      'Auditor',
      'TigistTesfaye.jpg',
      '25',
      5),
  Employee(
      41,
      'ፍሬው ተሻለ',
      'Fireew Tashaala',
      'Firew Teshale',
      'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi',
      'Auditor',
      '',
      '25',
      5),
  Employee(
      42,
      'ሮማን ዲበኩሉ',
      'Roomaan Dibakulluu',
      'Roman Dibekulu',
      'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi',
      'Auditor',
      '',
      '25',
      5),
  Employee(
      43,
      'ንጋቱ ይዘንጋው',
      'Nigaatuu Yaazangaaw',
      'Negatu Yezengaw',
      'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi',
      'Auditor',
      'NigatuYizengaw.jpg',
      '25',
      5),

  // Vehicle Inspection Team
  Employee(
      44,
      'ኤፍሬም አበራ',
      'Efireem Abaraa',
      'Ephrem Abera',
      'የተሸከርካሪ ቴክኒክ ምርመራ ባለሙያ',
      'Ogeessa Teekniikaa',
      'Vehicle Technical Inspection officer',
      'EphremAbera.jpg',
      '3',
      6),
  Employee(
      45,
      'በሱፍቃድ ሲሳይ',
      'Basufiqaad Sisaay',
      'Besufekad Sisay',
      'የተሸከርካሪ ቴክኒክ ምርመራ ባለሙያ',
      'Ogeessa Teekniikaa',
      'Vehicle Technical Inspection officer',
      'BesufekadSisay.jpg',
      '3',
      6),
  Employee(
      46,
      'ፉአድ ሁሴን',
      'Fuaad Huseen',
      'Fuad Husen',
      'የተሸከርካሪ ቴክኒክ ምርመራ ባለሙያ',
      'Ogeessa Teekniikaa',
      'Vehicle Technical Inspection officer',
      'FuadHussien.jpg',
      '4',
      6),
  Employee(47, 'ሪያድ አደም', 'Riyaad Adam', 'Riyad Adem', 'የተሸከርካሪ ቴክኒክ ምርመራ ባለሙያ',
      'Ogeessa Teekniikaa', 'Vehicle Technical Inspection officer', '', '5', 6),
  Employee(
      48,
      'ፌቭነ እሸቱ',
      'Feevan Isheetu',
      'Feven Eshetu',
      'የተሸከርካሪ ቴክኒክ ምርመራ ባለሙያ',
      'Ogeessa Teekniikaa',
      'Vehicle Technical Inspection officer',
      'FevenEshetu.jpg',
      '8',
      6),
];
