class Employee {
  int id;
  String amharic_name;
  String oromic_name;
  String english_name;
  String position;
  String oromic_position;
  String english_position;
  String path;
  String office;
  int team_id;
  bool hasSub;

  Employee(
      this.id,
      this.amharic_name,
      this.oromic_name,
      this.english_name,
      this.position,
      this.oromic_position,
      this.english_position,
      this.path,
      this.office,
      this.team_id,
      {this.hasSub = false});
}

List<Employee> Employees = [
  Employee(1, 'አወቀ ታደሰ በዛብህ', 'Aweqe tadse', 'Aweke tadese ', 'ዋና ስራ አስኪያጅ',
      'Darectara Tajajila konkolootaaa', 'Manager', 'AwekeTadese.jpg', '40', 0,
      hasSub: true),
  Employee(
      2,
      'መብራት ሀጎስ',
      'Mebraat Haggos ',
      'Mebrat Hagos',
      'የአሽከርካሪ ብቃት ማረጋገጥ ዳይሬክተር',
      'Hogganaa Damee',
      'Driver Service Director',
      '',
      '30',
      0,
      hasSub: true),
  Employee(
      3,
      'ፋኖስ መኮንን ',
      'Fanos Mekonen Gemeda',
      'Faanoos Makonnin ',
      'የተሸከርካሪ ብቃት ማረጋገጥ ፈቃድ አገልግሎት ዳይሬክተር',
      'Darectara Tajajila konkolootaaa',
      'Vehicle Service Director',
      'FanosMekonnen.jpg',
      '28',
      0,
      hasSub: true),
  Employee(
      4,
      'ኩኖ ዋቅጅራ',
      'Kuno Wakejra',
      'Kuunoo waqjiraa',
      'የግዥ፣ ፋይናንስና ንብረት አስተዳደር ዳይሬክተር',
      'Darekatara Faaynansii',
      'Finance and Asset Management Director',
      'KennoWakjira.jpg',
      '42',
      0,
      hasSub: true),
  Employee(
      5,
      'ያየሽ መኮንን',
      'Yaayesh Makonnin',
      'Yayesh Mekonen',
      'የአገልግሎት ጥራት ኦዲት ቡድን መሪ',
      'Hoganaa garee odiitii',
      'Audit team leader',
      '',
      '25',
      0,
      hasSub: true),
  Employee(
      6,
      'ዘሚካኤል የማነ አሰፋ',
      'Zamikaael Yemaana',
      'Zemikael Yemane Asefa',
      'የተሸከርካሪ ብቃት ማረጋገጥ ቡድን መሪ',
      'Dursaa garee Ogeessa Teekniikaa',
      'Vehicle Technical Inspection Team Leader',
      'ZemichaelYemane.jpg',
      '1',
      2,
      hasSub: true),
  // Team Manager
  Employee(
      7,
      'ራህመት ሁሴን መሀመድ',
      'Rahmet Hussene ',
      'Rahmet Hussene',
      'ኤክስኩቲቭ ሴክሬተሪ',
      'Barreessitu Hoji-geggeessaa',
      'Executive secretaries ',
      'RahmetHussen.jpg',
      '40',
      1,
      hasSub: true),
  Employee(8, 'ዮሃንስ ሙሉጌታ', 'Yohanes Mullugeta', 'Yohannes Mulugeta ',
      'አይ ሲቲ ባለሙያ', 'ICT', 'ICT', 'YohannesMulugeta.jpg', '41', 1),

  // Team Driver Service
  Employee(
      9,
      'ግርማ ወልዴ ለማ',
      'Girmaa Weldee ',
      'Girma Welde',
      'የአሽከርካሪ አገልግሎት ባለሙያ',
      'Ogeessa tajajilaa konkolootaaa',
      'Driver Service officer',
      'GirmaWolde.jpg',
      '31',
      2),
  Employee(
      10,
      'ጌቱ ብርሃኑ ሁሪሳ',
      'Getu Beraanu ',
      'Getu Brhanu',
      'የአሽከርካሪ አገልግሎት ባለሙያ',
      'Ogeessa tajajilaa konkolootaaa',
      'Driver Service officer',
      'GetuBerhanu.jpg',
      '32',
      2),
  Employee(
      11,
      'ሽኩሪያ ሀያቱ ሻሚል',
      'Shekuriya Hayatu ',
      'Shekuriiya Hayyatu ',
      'የአሽከርካሪ አገልግሎት ባለሙያ',
      'Ogeessa tajajilaa konkolootaaa',
      'Driver Service officer',
      'ShukriyaHayatu.jpg',
      '33',
      2),
  Employee(
      12,
      'አስቴር ገመቹ አብዲሳ',
      'Astter Gemechuu ',
      'Aster Gemechu',
      'የአሽከርካሪ ዳታ ኢንከደር',
      'Daataa inkoderaa',
      'Data incoder',
      'AsterGemechu.jpg',
      '31',
      7,
      hasSub: true),

  // Team Vehicle Service
  Employee(
      13,
      'ዘላለም  ምስጋና ',
      'Ogeessa tajajilaa konkolootaaa',
      'Zelalem Misgana',
      'የተሸከርካሪ ፈቃድ አገልግሎት ቡድን መሪ',
      'Dursaa goree Tajajila konkolootaaa',
      'Driver Service officer',
      'ZelalemMesgane.jpg',
      '24',
      12),
  Employee(
      14,
      'ታምራት ጌታነህ',
      'Taamiraat Getaana',
      'Tamrat Getaneh',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'TamiratGetaneh.jpg',
      '7',
      3),
  Employee(
      15,
      'ተዘራ ፍሬው',
      'Tazarraa Fireew',
      'Tezera Ferew',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'TezeraFirew.jpg',
      '17',
      3),
  Employee(
      16,
      'ዙፋን መክብብ',
      'Zufan Makbib',
      'Zufan Mekebeb',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'ZufanMekbeb.jpg',
      '15',
      3),
  Employee(
      17,
      'ጥላሁን ሚኒሊክ ',
      'Xilaahun Minilik',
      'Tilhun Minilik',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'TilahunMinilik.jpg',
      '12',
      3),
  Employee(
      18,
      'ሰላም ተሰራ',
      'Salaam Tasaraa',
      'Selam Tesera',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'SelamTesera.jpg',
      '14',
      3),
  Employee(
      19,
      'ከተማ መርጋ',
      'Katamaa Margaa',
      'Ketema Merga',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'KetemaMerga.jpg',
      '11',
      3),
  Employee(
      20,
      'መሃዲሱ ጅማ',
      'Mahaandisuu Jamaa',
      'Mehandisu Jema',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      '',
      '19',
      3),
  Employee(
      21,
      'ፀዳለ በርሄ',
      'Tsedale Barhee',
      'Tsedale Berhe',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'Tsedale.jpg',
      '13',
      3),
  Employee(
      22,
      'ላመነው ዋሴ',
      'Laamanaw Waasee',
      'Lamenew Wase',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'LamenewWase.jpg',
      '9',
      3),
  Employee(
      23,
      'ደረጄ ሸዋአመነ',
      'Derejjee ShawaaAmenee',
      'Dereje ShewaAmene',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'DerejeShewa.jpg',
      '16',
      3),
  Employee(
      24,
      'መብራቱ መኮንን',
      'Mabraatee Makonniin',
      'Mebrate Mekonin',
      'የተሸከርካሪ ዳታ ኢንኮደር ባለሙያ ',
      'Daataa Inkoodarii',
      'Data in coder ',
      'MebratuMekonne.jpg',
      '26',
      3),
  Employee(
      25,
      'በውቀት ደምለው',
      'Bawqatu Damlaw ',
      'Bewketu Demilew',
      'መረጃ ዴስክ',
      'Deeskii Odeefannoo',
      'Information Desk officer',
      'BewketuDemlew.jpg',
      '10',
      3),
  Employee(
      26,
      'መልካምፍሬ አዳነ',
      'Mabraatee Makonniin',
      'Mebrate Mekonin',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      'MelkamFireAdane.jpg',
      '',
      3),
  Employee(
      27,
      'ትዕግስት አዳነ',
      'Mabraatee Makonniin',
      'Mebrate Mekonin',
      'የተሸከርካሪ ፈቃድ አገልግሎት ባለሙያ',
      'Ogeessa tajaajilaa Konkocachisaa',
      'Vehicle Service officer',
      '',
      '',
      3),

  // Finanace Team
  Employee(
      28,
      'እየሩሰ ደሳለኝ',
      'Iyaruus Dasaakany',
      'Eyerus desalegn',
      'የፋይናንስ ቡድን መሪ',
      'Dursaa garee faynansii',
      'Finance team leader ',
      'EyerusalemDesalegn.jpg',
      '42',
      4),
  Employee(29, 'ትናኝ ችሎት', 'Tanaanyi chiloot', 'Tenagn Chelot', 'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii', 'Accountant', '', '42', 4),
  Employee(30, 'ድርቤ ዘውዴ', 'Daribee Zawdee', 'Deribe Zewde', 'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii', 'Accountant', 'DiribeZewde.jpg', '42', 4),
  Employee(31, 'ሰለሞን ታዬ', 'Salamoon Taayyee', 'Solomon Taye', 'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii', 'Accountant', 'SolomonTaye.jpg', '42', 4),
  Employee(32, 'እታገኝ አስፋው', 'Itaagany Asfaaw', 'Etagegnew Asfaw', 'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii', 'Accountant', 'EtagegnAsfaw.jpg', '42', 4),
  Employee(
      33,
      'ውብዓለም ብርሃኑ ',
      'Wubaalam Birhaanu',
      'Wubalem Birhanu',
      'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii',
      'Accountant',
      'WubalemBirhanu.jpg',
      '42',
      4),
  Employee(34, 'ብርቅነሽ አያሌው', 'Birqinash Ayaalew', 'Birkinesh Ayalew',
      'የሂሳብ ባለሙያ', 'Ogeessa  faynansii', 'Accountant', 'Berknesh.jpg', '42', 4),
  Employee(35, 'ሰርካለም ጌታነህ', 'Sarkaalam Getaanah', 'Serkalem Getaneh',
      'የሂሳብ ባለሙያ', 'Ogeessa  faynansii', 'Accountant', 'Serkalem.jpg', '42', 4),
  Employee(36, 'ገነት ጌታ', 'Gannat Geetaa', 'Genet Geta', 'የሂሳብ ባለሙያ',
      'Ogeessa  faynansii', 'Accountant', 'GenetGeta.jpg', '42', 4),
  // Team Odit
  Employee(
      37,
      'አብዲዋቅ ቦከና',
      'Abdiwaaq Bokennaa',
      'Abdiwak Bokena',
      'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi',
      'Auditor',
      '',
      '25',
      5),
  Employee(38, 'ታዬ ዘውዱ', 'Tayyee Zawduu', 'Taye Zewdu', 'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi', 'Auditor', 'TayeZewdu.jpg', '25', 5),
//   Employee(
//       39,
//       'አብዲዋቅ ቦከና',
//       'Abdiwaaq Bokennaa',
//       'Abdiwak Bokena',
//       'የአገልግሎት ጥራት ኦዲት ባለሙያ',
//       'Ogeessa tajajilaa Oditi',
//       'Auditor',
//       'AwekeTadese.jpg',
//       '25',
//       5),
  Employee(
      40,
      'ትዕግስት ተስፋዬ',
      'Tigist Tasfaye',
      'Tigist Tesfaye',
      'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi',
      'Auditor',
      'TigistTesfaye.jpg',
      '25',
      5),
  Employee(
      41,
      'ፍሬው ተሻለ',
      'Fireew Tashaala',
      'Firew Teshale',
      'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi',
      'Auditor',
      '',
      '25',
      5),
  Employee(
      42,
      'ሮማን ዲበኩሉ',
      'Roomaan Dibakulluu',
      'Roman Dibekulu',
      'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi',
      'Auditor',
      '',
      '25',
      5),
  Employee(
      43,
      'ንጋቱ ይዘንጋው',
      'Nigaatuu Yaazangaaw',
      'Negatu Yezengaw',
      'የአገልግሎት ጥራት ኦዲት ባለሙያ',
      'Ogeessa tajajilaa Oditi',
      'Auditor',
      'NigatuYizengaw.jpg',
      '25',
      5),

  // Vehicle Inspection Team
  Employee(
      44,
      'ኤፍሬም አበራ',
      'Efireem Abaraa',
      'Ephrem Abera',
      'የተሸከርካሪ ቴክኒክ ምርመራ ባለሙያ',
      'Ogeessa Teekniikaa',
      'Vehicle Technical Inspection officer',
      'EphremAbera.jpg',
      '3',
      6),
  Employee(
      45,
      'በሱፍቃድ ሲሳይ',
      'Basufiqaad Sisaay',
      'Besufekad Sisay',
      'የተሸከርካሪ ቴክኒክ ምርመራ ባለሙያ',
      'Ogeessa Teekniikaa',
      'Vehicle Technical Inspection officer',
      'BesufekadSisay.jpg',
      '3',
      6),
  Employee(
      46,
      'ፉአድ ሁሴን',
      'Fuaad Huseen',
      'Fuad Husen',
      'የተሸከርካሪ ቴክኒክ ምርመራ ባለሙያ',
      'Ogeessa Teekniikaa',
      'Vehicle Technical Inspection officer',
      'FuadHussien.jpg',
      '4',
      6),
  Employee(47, 'ሪያድ አደም', 'Riyaad Adam', 'Riyad Adem', 'የተሸከርካሪ ቴክኒክ ምርመራ ባለሙያ',
      'Ogeessa Teekniikaa', 'Vehicle Technical Inspection officer', '', '5', 6),
  Employee(
      48,
      'ፌቭነ እሸቱ',
      'Feevan Isheetu',
      'Feven Eshetu',
      'የተሸከርካሪ ቴክኒክ ምርመራ ባለሙያ',
      'Ogeessa Teekniikaa',
      'Vehicle Technical Inspection officer',
      'FevenEshetu.jpg',
      '8',
      6),
];

// List<Employee> Employees = [
//   Employee(1, 'ዲዳ ድሪባ', 'Dida Diriba', 'Dida Diriba', 'ዋና ስራ አስኪያጅ',
//       'Hoji-geggeessaa', 'Manager', 'dida_diriba.jpg', ' B-01   201', 0,
//       hasSub: false),
//   Employee(
//       2,
//       'አዱኛ ወንድሙ',
//       'Adugna Wendimu',
//       'Adugna Wendimu',
//       'የአካባቢ ጥበቃ ባለስልጣን አማካሪ',
//       'Environmental Protection Officer',
//       'Environmental Protection Officer',
//       'adugna_wendimu.jpg',
//       'B-01 304',
//       0,
//       hasSub: false),
//   Employee(
//       3,
//       'አንበሳው ፈንቴ',
//       'Anbesaw Fente',
//       'Anbesaw Fente',
//       'የአካባቢ ትምህርት ግንዛቤ ቡድን',
//       'Garee Hubannoo Barnoota Naannoo',
//       'Environmental Education Team',
//       'anbesaw_fente.jpg',
//       'B-01 104',
//       0,
//       hasSub: false),
//   Employee(
//       4,
//       'አስቴር አድማሱ',
//       'Aster Admasu',
//       'Aster Admasu',
//       'የላቦራቶሪ ክፍል ቡድን',
//       'Kutaa Laaboraatoorii',
//       'Laboratory Section Team',
//       'aster_admasu.jpg',
//       'B-02 001',
//       0,
//       hasSub: false),
//   Employee(
//       5,
//       'እህተ ከበደ',
//       'Ehte Kebede',
//       'Ehte Kebede',
//       'የውስጥ ኦዲት ዳይሬክቶሬት',
//       'Daayirektoreetii Odiitii Keessaa',
//       'Internal Audit Directorate',
//       'ehte_kebede.jpg',
//       'B-02 101',
//       0,
//       hasSub: false),
//   Employee(
//       6,
//       'እጅጋየሁ ካሳ',
//       'Ejigayehu Kasa',
//       'Ejigayehu Kasa',
//       'የሰው ኃብት አስተዳደር ዳይሬክቶሬት',
//       'Daayirektoreetii Bulchiinsa Humna Namaa',
//       'Human Resource Management Directorate',
//       'ejigayehu_kasa.jpg',
//       'B-01 101',
//       0,
//       hasSub: false),
//   Employee(
//       7,
//       'እንዳሻው ለገሰ',
//       'Endashaw Legesse',
//       'Endashaw Legesse',
//       'ግዥ ዳይሬክቶሬት',
//       'Daayirektoreetii Bittaa',
//       'Procurement Directorate',
//       'endashaw_legesse.jpg',
//       'B-01 103',
//       0,
//       hasSub: false),
//   Employee(
//       8,
//       'ውባየሁ ግርማ',
//       'Wibayehu Girima',
//       'Wibayehu Girima',
//       'ዕቅድና በጀት ዝግጅት ክትትልና ግምገማ ዳይሬክቶሬት',
//       'Ramaddii Karooraa fi Baajata Daayirektoreetii fi gamaaggamaa',
//       'Planning, Budgeting, Monitoring and Evaluation Directorate',
//       'wibayehu_girima.jpg',
//       'B-02 109',
//       0,
//       hasSub: false),
//   Employee(
//       9,
//       'ሃይሉ ጸጋዬ',
//       'Haylu Tsegaye',
//       'Haylu Tsegaye',
//       'ማዕድን ፈቃድ አስተዳደር ዳይሬክቶሬት',
//       'Daarektoreetii Bulchiinsa Hayyama Albuudaa',
//       'Directorate of Mining License Management',
//       'haylu_tsegaye.jpg',
//       'B-01 204',
//       0,
//       hasSub: false),
//   Employee(
//       10,
//       'ለሜሳ ጉደታ',
//       'Lamisa Gudeta',
//       'Lemisa Gudeta',
//       'አካባቢ ብክለት ጥናት ህግ ተከባሪነት አካባቢ ተፅዕኖ ግምገማ ዳይሬክቶሬት',
//       'Daayirektoreetii Madaallii Dhiibbaa Naannoo, Seera Baasuu fi Ulaagaa',
//       'Environmental Impact Assessment, Legislation and Compliance Directorate',
//       'lemisa_gudeta.jpg',
//       'B-01 305',
//       0,
//       hasSub: false),
//   Employee(
//       11,
//       'መላኩ ጋሪ',
//       'Malaku Gari',
//       'Melaku Gari',
//       'የኢነርጂ ኦዲት ፍቃድ ቡድን',
//       'Garee Odiitii fi Hayyama Annisaa',
//       'Energy Audit and License Team',
//       'melaku_gari.jpg',
//       'B-01 301',
//       0,
//       hasSub: false),
//   Employee(
//       12,
//       'መልካሙ ሰውነት',
//       'Malkamu Sawnet',
//       'Melkamu Sewnet',
//       'የማዕድን ፈቃድ አስተዳደር ቁጥጥር ቡድን',
//       'Garee To\'annoo Bulchiinsa Hayyama Albuudaa',
//       'Mining License Management Control Team',
//       'melkamu_sewnet.jpg',
//       'B-01 205',
//       0,
//       hasSub: false),
//   Employee(
//       13,
//       'መሰረት ግርማ',
//       'Meseret Girma',
//       'Meseret Girma',
//       'የንብረትና ጠቅላላ አገልግሎት ቡድን',
//       'Garee Qabeenyaa fi Tajaajila Waliigalaa',
//       'Property and General Service Team',
//       'meseret_girma.jpg',
//       'B-01 004',
//       0,
//       hasSub: false),
//   Employee(
//       14,
//       'ሙክታር ሰይድ',
//       'Muktar Seyid',
//       'Muktar Seyid',
//       'የኮምኒኬሽን ጉዳዮች ዳይሬክቶሬት',
//       'Daayirektoreetii Dhimmoota Komunikeeshinii',
//       'Communication Affairs Directorate',
//       'muktar_seyid.jpg',
//       'B-01 403',
//       0,
//       hasSub: false),
//   Employee(
//       15,
//       'ነጻነት ሞላ',
//       'Netsanet Molla',
//       'Netsanet Molla',
//       'ፋይናንስ ዳይሬክቶሬት',
//       'Daayirektoreetii Faayinaansii',
//       'Finance Directorate',
//       'netsanet_molla.jpg',
//       'B-01 001',
//       0,
//       hasSub: false),
//   Employee(
//       16,
//       'ሳሙኤል ተስፋዬ',
//       'Samule Tesfaye',
//       'Samuel Tesfaye',
//       'የስርዓተ ምህዳርና ብዝሀ ህይወት ጥናትና ምርምር ቡድን',
//       'Garee Qorannoo fi Misooma Sirna Ikoo fi Heddummina Lubbu qabeeyyii',
//       'Ecosystem and Biodiversity Research and Development Team',
//       'samuel_tesfaye.jpg',
//       'B-01 107',
//       0,
//       hasSub: false),
//   Employee(
//       17,
//       'ሰይድ አብድላ',
//       'Seyd Abdela',
//       'Seyd Abdela',
//       'የአየር ንብረት ለውጥና አማራጭ ኢነርጂ ቴክኖሎጂ ዳይሬክተር',
//       'Daarektarri Jijjiirama Qilleensaa fi Teeknooloojii Annisaa Filannoo',
//       'Director of Climate Change and Alternative Energy Technology',
//       'seyd_abdela.jpg',
//       'B-01 305',
//       0,
//       hasSub: false),
//   Employee(
//       18,
//       'ሽመልስ ምትኬ',
//       'Shimelis Mitike',
//       'Shimelis Mitike',
//       'የህንፃ አስተዳደርና ጥገና አገልግሎት ቡድን',
//       'Garee Tajaajila Bulchiinsa Gamoo fi Suphaa',
//       'Building Management and Maintenance Service Team',
//       'shimelis_mitike.jpg',
//       'B-02 103',
//       0,
//       hasSub: false),
//   Employee(
//       19,
//       'ሰለሞን መለሰ',
//       'Solomon Melesse',
//       'Solomon Melesse',
//       'የሙቀት አማቂ ጋዞችና ልኬት ቅነሳና አረንጓዴ ቴክኖሎጂ ማስፋፋት ቡድን',
//       'Garee Babal\'ina Teeknooloojii Ho\'isaa, Qilleensaa fi Qilleensaa',
//       'Heating, Ventilation and Air Conditioning Technology Expansion Team',
//       'solomon_melesse.jpg',
//       'B-01 203',
//       0,
//       hasSub: false),
//   Employee(20, 'ታድሶ አበባው', 'Tadso Abebaw', 'Tadso Abebaw', 'የጽ/ቤት ኃላፊ',
//       'Hogganaa waajjira', 'Office Manager', 'tadso_abebaw.jpg', 'B-01 402', 0,
//       hasSub: false),
//   Employee(
//       21,
//       'ቴዎድሮስ ይታገሡ',
//       'Tewodros Yitagesu',
//       'Tewodros Yitagesu',
//       'የብዝሃ ሕይወትና ስርዓተ ምህዳር ግንዛቤ ክትትልና ቁጥጥር ቡድን መሪ',
//       'Hogganaa Garee Hordoffii fi To\'annoo Bulchiinsa Heddummina Lubbu qabeeyyii fi Sirna Ikoo Naannoo',
//       'Head of Biodiversity and Ecosystem Management Monitoring and Control Team',
//       'tewodros_yitagesu.jpg',
//       'B-01 401',
//       0,
//       hasSub: false),
//   Employee(
//       22,
//       'ተመስገን ሁንደራ',
//       'Temesgen Hundera',
//       'Temesgen Hundera',
//       'የስነምግባርና ፀረሙስና ዳይሬክቶሬት',
//       'Daayirektoreetii Naamusaa fi Farra Malaammaltummaa',
//       'Ethics and Anti-Corruption Directorate',
//       'temesgen_hundera.jpg',
//       'B-01 305',
//       0,
//       hasSub: false),
//   Employee(
//       23,
//       'ተናኜ ነገሰ',
//       'Tenagne Negese',
//       'Tenagne Negese',
//       'የህንፃ አስተዳደር ጽ/ቤት ኃላፊ',
//       'Hogganaa Waajjira Bulchiinsa Gamoo',
//       'Building Management Office Manager',
//       'tenagne_negese.jpg',
//       'B-01 103',
//       0,
//       hasSub: false),
//   Employee(
//       24,
//       'ተዋበች ገብሬ',
//       'Tewabech Gebre',
//       'Tewabech Gebre',
//       'የፋሲሊቲ አገልግሎት ቡድን',
//       'Garee Tajaajila Faasilitii',
//       'Facility Service Team',
//       'tewabech_gebre.jpg',
//       'B-01 002',
//       0,
//       hasSub: false),
//   Employee(
//       25,
//       'አሰግደዉ ኃ/ጊዮርጊስ',
//       'Assegidew H/Giyorgis',
//       'Asegdew H/Giyorgis',
//       'ምክትል ስራ አስኪያጅ / የስርዓተ ምህዳርና የማዕድን አስተዳደር',
//       'Itti Aanaa Hogganaa / Bulchiinsa Sirna Ikoo fi Albuudaa',
//       'Deputy Manager / Ecosystem and Mining Management',
//       'assegidew_h_giyorgis.jpg',
//       'B-01 206',
//       0,
//       hasSub: false),
//   Employee(
//       26,
//       'ሙሉቀን ዮናስ',
//       'Muluken Yonas',
//       'Muluken Yonas',
//       'ምክትል ስራ አስኪያጅ / አካባቢ ብክለትና የአየር ንብረት ለውጥ ዘርፍ',
//       'Itti Aanaa Hogganaa / Kutaa Eegumsa Naannoo fi Jijjiirama Qilleensaa',
//       'Deputy Manager / Environmental Protection and Climate Change Section',
//       'muluken_yonas.jpg',
//       'B-01 303',
//       0,
//       hasSub: false),
//   Employee(
//       27,
//       'አማኑኤር ሽብሩ',
//       'Amanuel Shibru',
//       'Amanuel Shibru',
//       'የደን ሀብት አጠቃቀም ቡድን መሪ',
//       'Hogganaa Garee Itti Fayyadama Qabeenya Bosonaa',
//       'Forest Resource Utilization Team Leader',
//       'amanuel_shibru.jpg',
//       'B-01 1  06',
//       0,
//       hasSub: false),
//   Employee(
//       28,
//       'ሰናይት ተስፋዬ',
//       'Senayit Tesfaye',
//       'Senayit Tesfaye',
//       'የብክለት ቁጥጥርና የአካባቢ ተፅዕኖ ግምገማ ቡድን',
//       'Garee To\'annoo Eegumsa Naannoo fi Madaallii Dhiibbaa',
//       'Environmental Protection and Impact Assessment Control Team',
//       'senayit_tesfaye.jpg',
//       'B-01 304',
//       0,
//       hasSub: false),
//   Employee(
//       29,
//       'ብርክቲ መለሰ',
//       'Birkti Melesse',
//       'Birkti Melesse',
//       'አየር ንብረት ለውጥና �ቅድ ዝግጅት ትግበራ ቡድን',
//       'Garee Raawwii Jijjiirama Qilleensaa fi Karoora',
//       'Climate Change and Planning Implementation Team',
//       'birkti_melesse.jpg',
//       'B-01 203',
//       0,
//       hasSub: false),
//   Employee(
//       30,
//       'ቴዎድሮስ ሽመልሽ',
//       'Tewodros Shimelesh',
//       'Tewodros Shimelesh',
//       'የነዳጅና የነዳጅ ውጤቶች ተቋማት ቡቃት ማረጋገጫ ቡድን',
//       'Garee Mirkaneessa Qulqullina Oomisha Boba\'aa fi Boba\'aa',
//       'Petroleum and Petroleum Products Quality Assurance Team',
//       '',
//       'B-01 006',
//       0,
//       hasSub: false),
//   Employee(31, 'የዉብዳር መለሰ', 'Yewibdar Melesse', 'Yewibdar Melesse', 'የግዥ ቡድን',
//       'Garee Bittaa', 'Procurement Team', '', 'B-01 103', 0,
//       hasSub: false),
//   Employee(
//       32,
//       'አለም ሰይድ',
//       'Alem Seyid',
//       'Alem Seyid',
//       'የኢንፎርሜሽን ቴክኖሎጂ ዳይሬክቶሬት',
//       'Daayirektoreetii Teeknooloojii Odeeffannoo',
//       'Information Technology Directorate',
//       '',
//       'B-01 013',
//       0,
//       hasSub: false),
//   Employee(
//       33,
//       'አንበሳዉ ፈንታ',
//       'Anbesaw Fenta',
//       'Anbesaw Fenta',
//       'የለውጥና መልካም አስተዳደር ዳይሬክቶሬት',
//       'Daayirektoreetii Jijjiiramaa fi Bulchiinsa Gaarii',
//       'Change and Good Governance Directorate',
//       '',
//       'B-02 108',
//       0,
//       hasSub: false),
//   Employee(34, 'ዳዊት አባተ', 'Dawit Abate', 'Dawit Abate', 'የህግ �ገልግሎት ቡድን',
//       'Garee Tajaajila Seeraa', 'Legal Service Team', '', 'B-02 104', 0,
//       hasSub: false),
// ];
